version: "3.3"

services:
  postgres:
      container_name: bbs-game-postgres
      image: postgres:11-alpine
      command: postgres -c max_connections=1000
      environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"
        POSTGRES_DB: bbs-game
        POSTGRES_USER: ps_user
        POSTGRES_PASSWORD: ps_password
        POSTGRES_HOST: postgres
      ports:
        - 7002:5432
